import { readFile, writeFile } from "node:fs/promises";
import { marked } from "marked";

const sectionIds = [
  "executive-summary",
  "methodology",
  "corridor-overview",
  "unmet-needs",
  "market-priority",
  "gulf-to-south-asia",
  "europe-to-asia",
  "asia-to-europe-gulf",
  "europe-gulf-to-africa",
  "global-to-latam",
  "us-to-global",
  "validation-plan",
  "limitations",
  "sources",
];

const reports = [
  { lang: "zh", source: new URL("../content/report.zh.md", import.meta.url) },
  { lang: "en", source: new URL("../content/report.en.md", import.meta.url) },
];

function stripTags(value) {
  return value
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

function prepareSource(source, lang) {
  let prepared = source.replace(/^# .+\n/, "");

  if (lang === "zh") {
    prepared = prepared
      .replace("用途：内部市场筛选与试点设计", "用途：市场研究与试点设计参考")
      .replace("## 十二、发送前逻辑漏洞清单", "## 十二、方法限制与数据说明");
  } else {
    prepared = prepared
      .replace(/Purpose:\s*Internal market screening and pilot design/i, "Purpose: Market research and pilot-design reference")
      .replace(/^##\s+12\..*(logic gap|pre-publication).*$/im, "## 12. Limitations and data notes");
  }

  return prepared;
}

function decorateHtml(rawHtml, lang) {
  let h2Index = 0;
  let h3Index = 0;
  const toc = [];

  let html = rawHtml.replace(/<h([1-3])>([\s\S]*?)<\/h\1>/g, (_, levelText, inner) => {
    const level = Number(levelText);
    const title = stripTags(inner);

    if (level === 1) return "";

    if (level === 2) {
      const id = sectionIds[h2Index];
      if (!id) throw new Error(`Unexpected extra H2 in ${lang}: ${title}`);
      h2Index += 1;
      h3Index = 0;
      toc.push({ id, title });
      return `<h2 id="${id}">${inner}<a class="heading-link" href="#${id}" aria-label="${lang === "zh" ? "链接到本节" : "Link to this section"}">#</a></h2>`;
    }

    h3Index += 1;
    const parentId = sectionIds[Math.max(h2Index - 1, 0)] ?? "section";
    const id = `${parentId}-${h3Index}`;
    return `<h3 id="${id}">${inner}</h3>`;
  });

  if (h2Index !== sectionIds.length) {
    throw new Error(`${lang} report has ${h2Index} H2 headings; expected ${sectionIds.length}`);
  }

  let tableIndex = 0;
  html = html
    .replace(/<table>/g, () => {
      tableIndex += 1;
      const caption = lang === "zh" ? `跨境支付走廊研究数据表 ${tableIndex}` : `Cross-border corridor research data table ${tableIndex}`;
      const label = lang === "zh" ? "可横向滚动的数据表" : "Scrollable data table";
      return `<div class="table-scroll" tabindex="0" role="region" aria-label="${label}"><table><caption class="sr-only">${caption}</caption>`;
    })
    .replace(/<\/table>/g, "</table></div>")
    .replace(/<th>/g, '<th scope="col">')
    .replace(/<a href="(https?:\/\/[^\"]+)"/g, '<a href="$1" rel="noreferrer"');

  return { html, toc, tableCount: tableIndex };
}

const generated = {};

for (const report of reports) {
  const source = await readFile(report.source, "utf8");
  const prepared = prepareSource(source, report.lang);
  const parsed = await marked.parse(prepared, { gfm: true });
  generated[report.lang] = decorateHtml(parsed, report.lang);
}

if (generated.zh.tableCount !== generated.en.tableCount) {
  throw new Error(`Table count mismatch: zh=${generated.zh.tableCount}, en=${generated.en.tableCount}`);
}

const output = `// Generated by scripts/generate-content.mjs. Do not edit directly.\n\n` +
  `export const reportZhHtml = ${JSON.stringify(generated.zh.html)};\n` +
  `export const reportEnHtml = ${JSON.stringify(generated.en.html)};\n` +
  `export const tocZh = ${JSON.stringify(generated.zh.toc, null, 2)} as const;\n` +
  `export const tocEn = ${JSON.stringify(generated.en.toc, null, 2)} as const;\n` +
  `export const reportTableCount = ${generated.zh.tableCount};\n`;

await writeFile(new URL("../content/generated.ts", import.meta.url), output);
